### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by Coffee-Powered-Scientist** [Coffee-Powered-Scientist/NutsFor_OR2#1]

**Comment by Juniper41** [comment]
You were very inviting as a presenter. Your research sounds very interesting and it looks like you have a good understanding of the challenges you anticipate facing throughout the project.

**Comment by howardre** [comment]
I like that you kept your slides simple and then just drew attention to your main points for each section.

**Comment by Angelika-Kurthen** [comment]
Hi Kaveh!

Despite not knowing anything about tree stand modelling, I really appreciated your presentation. As you talked through the challenges of the project, I think I got an even better understanding of your project structure and how you plan on tackling them. Finally, I really appreciated the candid goals (i.e. write thesis, etc).

**Comment by jwongala** [comment]
I enjoyed learning about your project and model. It reminds me of similar models used in oceanography. Also nice and clean presentation.

**Comment by zechmeunier** [comment]
Writing a manual along with the modeling would be impressive!

**Comment by McLeodMJ** [comment]
Hi Kaveh!
Very cool research! I understand the circular challenges of simulated vs observed values and am curious to see how you will update your code to better retrieve your outputs. That would definitely be helpful for running my own simulations as well.

**Comment by jessealaney** [comment]
Interesting project, Kaveh. The circular nature of your modeling seems like it presents challenges, but you also seem to have a good understanding of those challenges. I know you said you were interesting in moving on from being a bug checker, but I'm happy to share code if you want more practice!

**Comment by breshears-logan** [comment]
In one of your slides you mentioned that one of the main nutrients you are tracking is Nitrogen. Is there any covariance associated with nitrogen and other nutrients, that may have an effect on your results?
