### ISSUE TITLE
Final Project Report

### ISSUE THREAD

**Issue by Coffee-Powered-Scientist** [Coffee-Powered-Scientist/NutsFor_OR2#15]

**Comment by howardre** [comment]
I think it's really cool that you were able to get portions of your thesis to auto-update, that sounds very convenient!

**Comment by McLeodMJ** [comment]
Hi Kaveh!
Great progress! Your repository is very impressive and thorough, and more importantly, easy to follow. Creating faster code is a big success so fantastic job there, I'm sure it will help you make progress on your final stretch of calibrations.

**Comment by Angelika-Kurthen** [comment]
It sounds like you got a lot of stuff done and are in good position to continue working!
