### ISSUE TITLE
Project Progress Report

### ISSUE THREAD

**Issue by Coffee-Powered-Scientist** [Coffee-Powered-Scientist/NutsFor_OR2#3]

**Comment by Angelika-Kurthen** [comment]
I think you did a great job describing your workflow and code. Your 2nd workflow was a little hard to read (discord makes the screen share really small).

**Comment by zechmeunier** [comment]
Terrific that you were able to simplify your code so extensively!

**Comment by jwongala** [comment]
Thanks for the refresher on your project. I enjoyed the workflow diagrams you created.

**Comment by Juniper41** [comment]
Your workflow was very clear and your streamlined code made it very easy to follow as an outsider. Great job!

**Comment by howardre** [comment]
It was great to see your workflow in detail, since I think it can be hard for those outside of your project to understand how you're going to accomplish your goals. Making the second one larger, or maybe just changing the way it is laid out on the slide, would make it easier to see.

**Comment by McLeodMJ** [comment]
Hi Kaveh! Your workflows are very detailed, which has made me realize I could probably benefit from doing the same, so thank you! Glad to hear your progress has made the script faster as well.

**Comment by jessealaney** [comment]
Look like you have a comprehensive workflow established. Your goals seem seasonable as well. Well done.
